name: publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm@v6.32.6
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Set up node@v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run test

  publish-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm@v6.32.6
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Set up node@v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - run: pnpm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
